title: stonks
name: stonks
markdown: kramdown
url: "https://ryness.github.io"
baseurl: "/stonks"
collections:
  reports:
    output: true
    permalink: /reports/:name/
permalink: pretty
exclude:
  - config
  - notes
  - src
  - tools
  - __pycache__
repository: ryness/stonks
