title: stonks
name: stonks
markdown: kramdown
url: "https://ryness.github.io"
baseurl: "/stonks"
collections:
  reports:
    output: true
    permalink: /reports/:name/
permalink: pretty
exclude:
  - tools
  - __pycache__
  - apikey-openai.txt
  - apikey-massive.txt
  - stock-expert_prompt.txt
  - gostonks.py
repository: ryness/stonks
